### ISSUE TITLE
undefined method 'version' for nil:NilClass

### ISSUE THREAD

**Issue by walkamongus** [voxpupuli/puppet-report_hipchat#10]
## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 4.7.0
- Ruby: jruby 1.7.26 (1.9.3p551)
- Distribution: RHEL 6
- Module version: commit d29770fc960b106c5834b33d9121c656f0cc44c7

## How to reproduce (e.g Puppet code you use)
install the module and set reports correctly

## What are you seeing
I'm getting the following error, which seems to stem from https://github.com/voxpupuli/puppet-report_hipchat/blob/master/lib/puppet/reports/hipchat.rb#L37:

`Error: Could not send report: Error 500 on SERVER: Server Error: Could not autoload puppet/reports/hipchat: undefined method 'version' for nil:NilClass`

## What behaviour did you expect instead
No Error when executing the report

## Any additional information you'd like to impart
If I execute the file directly using puppetserver's Ruby, I see the gem:

```
~]# GEM_HOME=/opt/puppetlabs/server/data/puppetserver/jruby-gems /opt/puppetlabs/server/bin/puppetserver ruby /opt/puppetlabs/puppet/cache/lib/puppet/reports/hipchat.rb
Gem::Specification.new do |s|
  s.name = "hipchat"
  s.version = Gem::Version.new("1.5.4")
...
```

**Comment by james-powis** [comment]
Code was initially implemented here: https://github.com/jamtur01/puppet-hipchat/pull/36

**Comment by james-powis** [comment]
@walkamongus can you please run the following: `puppetserver gem list hipchat`

**Comment by walkamongus** [comment]
Hi @james-powis -- the output above was from the same puppetserver where the issue is occurring and shows the hipchat gem version as `1.5.4`.

Do you need the literal output of the `puppetserver gem` command? Let me know and I can grab it.

**Comment by james-powis** [comment]
@walkamongus I would prefer so, every time I have seen the error you are describing was due to the gem not actually being available to puppetserver. In short if the output spits out a version then we have something new and fun to identify, if it does not then `puppetserver gem install hipchat` should fix your issue.

**Comment by walkamongus** [comment]
@james-powis  -- sure thing...here it is:
```
~]# /opt/puppetlabs/server/bin/puppetserver gem list hipchat
*** LOCAL GEMS ***

hipchat (1.5.4)
```

**Comment by james-powis** [comment]
@walkamongus If you check the puppetserver log I am willing to bet you are going to see this on the first report observed after a reload of puppetserver: `You need the `hipchat` gem to use the Hipchat report`

I am betting the GEM_HOME and/or PATH are being overriden. Perhaps RVM is in use given you are running CENT 6 and this module... In that scenario you have to use the RVM provided gem to install the hipchat gem.

**Comment by walkamongus** [comment]
Hi @james-powis,

Thanks for your help. I actually think I just found the issue and it seems to be specific to Puppet Enterprise. It appears that permissions were not correct on directories of the gem itself (down in `/opt/puppetlabs/server/data/puppetserver/jruby-gems/gems`) when installed via `puppetserver gem`. Permissions were set to 0750 and this prevents the puppetserver user (pe-puppet) from being able to access the directories. Perms of 0755 fixed the issue and the error is now gone.

**Comment by james-powis** [comment]
@walkamongus I believe the cause of the issue you encountered is logged here: https://tickets.puppetlabs.com/browse/ENTERPRISE-552
