### ISSUE TITLE
Package hipchat not getting installed

### ISSUE THREAD

**Issue by induja0107** [voxpupuli/puppet-report_hipchat#20]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.6.0
- Ruby:
- Distribution:
- Module version: latest

## How to reproduce (e.g Puppet code you use) 
```puppet
  class { 'report_hipchat':
    server         => 'https://hipchat.domain.com',
    api_version    => 'v2',
    api_key        => 'redacted',
    room           => 'redacted',
    config_file    => '/etc/puppetlabs/puppet/hipchat.yaml',
    install_hc_gem => true,
    provider       => 'puppetserver_gem',
    proxy          => 'http://proxyserver.domain.com:8080',
    package_name   => 'hipchat',
  }
```
## What are you seeing
I am not seeing that the package hipchat is being installed.
## What behaviour did you expect instead
Since i set install_hc_gem to true, i expected package hipchat to be installed. 
## Output log
No error messages. /etc/puppetlabs/puppet/hipchat.yaml gets created but the package doesn't get installed.
## Any additional information you'd like to impart
The puppetserver_gem puppetlabs module is installed through r10k control repo.

**Comment by james-powis** [comment]
@induja0107 can you please run `puppetserver gem list | grep hipchat` and provide the output,

Additionally can you please let us know if you are running opensource or PE and at what version.

**Comment by induja0107** [comment]
Sorry, it was an understanding issue. When i do a sudo puppetserver gem list | grep hipchat, i get this:

hipchat (1.5.4)

I was expecting that it would listed as one of the puppet resources installed. 

And i was using open source puppet BTW.

Thanks for looking into it. Appreciate your help!
