### ISSUE TITLE
Incompatibilty puppet 3

### ISSUE THREAD

**Issue by eraffaelli** [voxpupuli/puppet-report_hipchat#23]
Hello,
First, I would like to give you a big thanks for your work on this plugin ;)

I found a misconception in the README. From the description on the forge page, it's indicated that puppet-report_hipchat is compatible with Puppet >= 3.8.7 but when you look to install it, you can see that a component named  'puppetserver_gem' is needed.
That component is not compatible with Puppet 3.X as the following link show https://forge.puppet.com/puppetlabs/puppetserver_gem/0.1.0/compatibility the oldest version 0.1.0 that it need at least Puppet 4.

Is it possible to replace puppetserver_gem with another provider? (manual gem install?). If not, I think that the requirement for Puppet4 need to be indicated in the README.

Cheer.
E.R

**Comment by james-powis** [comment]
Your absolutely right! however its important to understand the history of the puppet report module, initially it was just a report processor, and it was extended to also install all the dependencies and build the config later. As such you can disable the management of the hipchat_gem via $install_hc_gem => false.

From there you can manually install gems into the appropriate puppet gem $path.

Alternatively you can set the provider via:

$provider => 'some other provider'

However you really should be looking into migrating to puppet 4

**Comment by ffrank** [comment]
Agreed. Fix should be to note Puppet 4 requirement in the docs.

It is my understanding that Vox Pupuli modules drop Puppet 3 support, as that has reached End Of Life.

**Comment by james-powis** [comment]
The module by default does not install the hipchat gem using the puppetserver_gem provider on puppet versions < 4.0.0:

```puppet
  } elsif ($::puppetversion) and (versioncmp('4.0.0', $::puppetversion) < 1) {
    $puppetconf_path = '/etc/puppetlabs/puppet'
    $install_hc_gem  = false
    $provider        = undef
    $owner           = 'puppet'
    $group           = 'puppet'
```

and given puppet 3 is EOL, I don't think anything code wise really needs to change... Perhaps just a foot note in the docs saying "for puppet 3 you are on your own to install the hipchat gem"

**Comment by eraffaelli** [comment]
It was just to notify that maybe the README needed to be updated ;)
Thanks for your answers.

Cheer.

**Comment by ffrank** [comment]
Re-opening because there is no fix yet.
