### ISSUE TITLE
IO Error Broken pipe on hipchat and httpparty gems

### ISSUE THREAD

**Issue by induja0107** [voxpupuli/puppet-report_hipchat#34]
I am getting the below mentioned error while executing class hipchat. I may be totally wrong here but i feel that the versions of the following are incorrect in report_hipchat/init.pp

Current hipchat version in rubygems.org: 1.6.0
Current httpparty version in rubygems.org: 0.0.7

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.10.9
- Module version: 2.0.0

## How to reproduce (e.g Puppet code you use) 
    $api_key = hiera(hipchat_api_key,'')

    class { 'report_hipchat':
      server         => 'http://hipchat.domain.com',
      api_version    => 'v2',
      api_key        => $api_key,
      room           => 'Puppet',
      config_file    => '/etc/puppetlabs/puppet/hipchat.yaml',
      install_hc_gem => true,
      provider       => 'puppetserver_gem',
      notify         => Service['puppetserver'],
    }
## What are you seeing

Error: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://<domain>/artifactory/rubygems/quick/Marshal.4.8/hipchat-1.5.4.gemspec.rz)
Error: /Stage[main]/Report_hipchat/Package[hipchat]/ensure: change from absent to ~> 1.5.0 failed: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://<domain>/artifactory/rubygems/quick/Marshal.4.8/hipchat-1.5.4.gemspec.rz)
    
Error: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://domain/artifactory/rubygems/quick/Marshal.4.8/httparty-0.14.0.gemspec.rz)
Error: /Stage[main]/Report_hipchat/Package[httparty]/ensure: change from absent to ~> 0.14.0 failed: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://domain/artifactory/rubygems/quick/Marshal.4.8/httparty-0.14.0.gemspec.rz)

## What behaviour did you expect instead

Hipchat and httpparty gems to be installed

## Output log
Error: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://<domain>/artifactory/rubygems/quick/Marshal.4.8/hipchat-1.5.4.gemspec.rz)
Error: /Stage[main]/Report_hipchat/Package[hipchat]/ensure: change from absent to ~> 1.5.0 failed: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://<domain>/artifactory/rubygems/quick/Marshal.4.8/hipchat-1.5.4.gemspec.rz)
    
Error: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://domain/artifactory/rubygems/quick/Marshal.4.8/httparty-0.14.0.gemspec.rz)
Error: /Stage[main]/Report_hipchat/Package[httparty]/ensure: change from absent to ~> 0.14.0 failed: Could not update: Could not install: ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    IOError: Broken pipe (https://domain/artifactory/rubygems/quick/Marshal.4.8/httparty-0.14.0.gemspec.rz)

**Comment by james-powis** [comment]
@induja0107 Based on the output it appears you have sanitized some of the output. I am assuming this is because you are running your own artifactory server which likely does not have these gems present. I would strongly recommend that you either manually install from rubygems.org or you stage the gems into your artifactory server.

**Comment by induja0107** [comment]
I will do that, thanks!
